---
- name: check to see if the etcd binary exists
  become: yes
  stat:
    path: /usr/local/bin/etcd
  register: etcd_binary

- name: disable and stop the service
  become: yes
  systemd:
    name: etcd
    daemon_reload: True
    state: stopped
    enabled: False
  when: etcd_binary.stat.exists

- name: remove previously setup files and directories
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/systemd/system/etcd.service
  - /var/lib/etcd
  - /usr/local/bin/etcd
  - /usr/local/bin/etcdctl
  - /usr/local/bin/kubeadm
  - /etc/kubernetes
