---
docker_debian_version: "{{ docker.debian.version if docker_debian_version_defined else '17.03.2~ce-0~ubuntu-xenial' }}"
docker_redhat_version: "{{ docker.redhat.version if docker_redhat_version_defined else '17.03.3.ce-1.el7' }}"
docker_logging_max_size: 100m
