---
- name: check whether we have joined this node
  become: yes
  shell: "/usr/bin/docker ps | /bin/grep kube-proxy"
  register: kube_proxy_running
  ignore_errors: True

- name: systemctl daemon-reload
  become: yes
  systemd:
    name: kubelet
    daemon_reload: true
    state: restarted

- name: join nodes to masters
  become: yes
  command: "/usr/bin/kubeadm join {{ kubernetes.apiLoadBalancer.ip }}:6443 --token='{{ kubeadm.token.value }}' --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=cri"
  when: kube_proxy_running is failed
