- name: download the calico yaml
  become: yes
  run_once: True
  delegate_to: "{{ groups['masters'] | first }}"
  get_url:
    url: "{{ calico.deploymentInstallUrl }}"
    dest: /tmp/calico.yaml
    force: yes

- name: replace the default pod CIDR
  become: yes
  run_once: True
  delegate_to: "{{ groups['masters'] | first }}"
  lineinfile:
    path: /tmp/calico.yaml
    regexp: "^(\\s+)value:\\s\"192.168.0.0\\/16\"$"
    line: "              value: \"{{ kubernetes.podCIDR }}\""

- name: apply the calico specs
  become: yes
  run_once: True
  delegate_to: "{{ groups['masters'] | first }}"
  shell: "kubectl apply -f {{ item }}"
  with_items:
  - "{{ calico.rbacInstallUrl }}"
  - "/tmp/calico.yaml"

- name: cleanup the calico install
  become: yes
  run_once: True
  delegate_to: "{{ groups['masters'] | first }}"
  file:
    path: /tmp/calico.yaml
    state: absent
