---
#- name: disable and stop docker
#  become: yes
#  systemd:
#    name: docker
#    daemon_reload: True
#    state: stopped
#    enabled: False

- name: uninstall docker
  become: yes
  yum:
    name: docker-ce
    state: absent

- name: uninstall docker ce selinux
  become: yes
  yum:
    name: docker-ce-selinux
    state: absent

- name: uninstall docker-selinux
  become: yes
  yum:
    name: docker-selinux
    state: absent

- name: check to see if pip is already installed
  become: yes
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: pip_is_installed

- name: uninstall docker-py
  become: yes
  pip:
    name: docker-py
    state: absent
  when: pip_is_installed.rc == 0

- name: remove previously created files and directories
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/docker
  - /etc/systemd/system/docker.service.d
  - /var/lib/docker



- name: remove docker repository clean yum metadata cache
  yum_repository:
    name: docker
    state: absent
  notify: 
  - yum clean metadata